#!/bin/sh
echo "These should run without errors:"
echo "-------------------------------------------------------------------"
echo "Declarations"
./tokenizer tests/declarations.txt | grep "Error"
echo "Conditionals"
./tokenizer tests/conditional.txt | grep "Error"
echo "While"
./tokenizer tests/while.txt | grep "Error"
echo "If/While"
./tokenizer tests/ifwhilesample.txt | grep "Error"
echo "Simple Source file from Assignment 1"
./tokenizer tests/simple.txt | grep "Error"
echo "-------------------------------------------------------------------"
echo "These should have errors:"
echo "-------------------------------------------------------------------"
./tokenizer tests/lexicalerror.txt | grep "Error"
./tokenizer tests/syntaxerror.txt | grep "Error"
./tokenizer tests/undefined.txt | grep "Error"
